### ISSUE TITLE
We are not able to add new plugin in this build

### ISSUE THREAD

**Issue by ashutoshb-ux** [SanketKarve/ckeditor5-mathtype#1]
Hi Sanket,

We are also integrating the CKEditor in react and we are not able to add new plugin in the custom build.
Can you please get in touch and guide us through this. It will be quite helpful.

Thanks
Ashutosh

**Comment by SanketKarve** [comment]
Sure.
You can check my profile for details to get in touch. Or suggest a safe channel for DM.

**Comment by ashutoshb-ux** [comment]
Ok ,
So I will ping you on linked in.
Thanks
